// resources/angular/src/app/shared/navbar/navbar.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent {
  isScrolled = false;

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isScrolled = window.scrollY > 0;
  }
}

<header [class.scrolled]="isScrolled">
    <div class ="container-fluid text-center">
        <div class="row">
            <div class="col-md-12">
                <nav>
                    <ul>
                    <li><a routerLink="/">Home</a></li>
                    <li><a routerLink="/biography">Biography</a></li>
                    <li><a routerLink="/portfolio">Portfolio</a></li>
                    <li><a routerLink="/investments">Investments</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

// resources/js/components/shared/navbar.tsx
import React from "react";
import { Link } from "react-router-dom";

export const Navbar = () => {

    return (
        <header>
            <div className ="container-fluid text-center">
                <div className="row">
                    <div className="col-md-12">
                    <nav>
                        <ul>
                        <li><Link to="/">Home</Link></li>
                        <li><Link to="/biography">Biography</Link></li>
                        <li><Link to="/portfolio">Portfolio</Link></li>
                        <li><Link to="/investments">Investments</Link></li>
                        </ul>
                    </nav>
                    </div>
                </div>
            </div>
      </header>
    )
};
